---
name: template
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite-dx
image-version: latest

modules:
  - type: dnf
    repos:
      copr:
        - matinlotfali/KDE-Rounded-Corners
    install:
      packages:
        - alsa-plugins-a52
        - kvantum
        - kwin-effect-roundcorners
        - liquidctl
        - mpv
        - openrgb
        - stow
    remove:
      packages:
        - lutris
        - waydroid

  - type: signing
