---
name: bazzite
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite-dx
image-version: latest

modules:
  - type: dnf
    install:
      packages:
        - alsa-plugins-a52
        - gwenview
        - kcalc
        - kvantum
        - liquidctl
        - mpv
        - okular
        - openrgb
        - stow
    remove:
      packages:
        - libvirt
        - lutris
        - qemu
        - Sunshine
        - waydroid

  - type: dnf
    install:
      packages:
        - cmake
        - gcc-c++
        - extra-cmake-modules
        - kwin-devel
        - kf6-kconfigwidgets-devel
        - libepoxy-devel
        - kf6-kcmutils-devel
        - kf6-ki18n-devel
        - qt6-qtbase-private-devel
        - wayland-devel
        - libdrm-devel

  - type: script
    scripts:
      - build_kde_rounded_corners.sh

  - type: dnf
    remove:
      packages:
        - cmake
        - gcc-c++
        - extra-cmake-modules
        - kwin-devel
        - kf6-kconfigwidgets-devel
        - libepoxy-devel
        - kf6-kcmutils-devel
        - kf6-ki18n-devel
        - qt6-qtbase-private-devel
        - wayland-devel
        - libdrm-devel

  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          title: Flathub (system)
        remove:
          - com.vysp3r.ProtonPlus
          - com.ranfdev.DistroShelf
          - com.github.Matoking.protontricks
          - it.mijorus.gearlever
          - org.kde.filelight
          - org.kde.haruna
          - org.freedesktop.Platform.VulkanLayer.MangoHud
          - org.freedesktop.Platform.VulkanLayer.vkBasalt
          - org.freedesktop.Platform.VulkanLayer.OBSVkCapture
          - com.obsproject.Studio.Plugin.OBSVkCapture
          - com.obsproject.Studio.Plugin.Gstreamer
          - com.obsproject.Studio.Plugin.GStreamerVaapi

  - type: signing
