---
name: template
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite-dx
image-version: latest

modules:
  - type: dnf
    repos:
      copr:
        - matinlotfali/KDE-Rounded-Corners
    install:
      packages:
        - alsa-plugins-a52
        - kvantum
        - kwin-effect-roundcorners
        - liquidctl
        - mpv
        - openrgb
        - stow
    remove:
      packages:
        - lutris
        - waydroid

  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          title: Flathub (system)
        remove:
        - com.github.Matoking.protontricks
        - it.mijorus.gearlever
        - org.kde.filelight
        - org.kde.haruna
        - org.freedesktop.Platform.VulkanLayer.MangoHud
        - org.freedesktop.Platform.VulkanLayer.vkBasalt
        - org.freedesktop.Platform.VulkanLayer.OBSVkCapture
        - com.obsproject.Studio.Plugin.OBSVkCapture
        - com.obsproject.Studio.Plugin.Gstreamer
        - com.obsproject.Studio.Plugin.GStreamerVaapi

  - type: signing
